    NUMPY ARRAY YAPISI

In [1]:
list=[1,2,3,4,5,6]
list

[1, 2, 3, 4, 5, 6]

In [3]:
# tek boyutlu numpy array kullanımı
import numpy as np
array=np.array(list)
array

array([1, 2, 3, 4, 5, 6])

In [4]:
# çok boyutlu numpy array kullanımı
liste=[[2,54,321],[12,4,96],[2,5,4]]
array=np.array(liste)
array

array([[  2,  54, 321],
       [ 12,   4,  96],
       [  2,   5,   4]])

In [6]:
# tek boyutlu numpy array kullanımı
array=np.array([4,5,32])
array

array([ 4,  5, 32])

In [10]:
# numpy array elemanlarına erişim
liste=[[2,54,321],[12,4,96],[2,5,4]]
array2=np.array(liste)
array2

array([[  2,  54, 321],
       [ 12,   4,  96],
       [  2,   5,   4]])

In [11]:
array2[1,2]

96

In [12]:
#arange methodu
np.arange(10,25)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [14]:
# tek boyutlu her bir elemanın 0 olduğu 10*10 array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
# tek boyutlu her bir elemanın 1 olduğu 10*10 array
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
# demetler ile farklı boyutlarda array oluşturma
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# linspace() methodu: belirli bir aralığı eşit parçaya bölme
np.linspace(10,100,4)

array([ 10.,  40.,  70., 100.])

In [19]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
# birim matris oluşturma
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
# random.randint() methodu: random değer üretmek
np.random.randint(0,100) 

35

In [22]:
np.random.randint(5) #0-5 aralığında

2

In [23]:
# üretilen random değerleri göstermek
np.random.randint(0,5,3)
# üretilen 3 tane random değeri array olarak gösterdi

array([1, 0, 2])

In [24]:
# rand() methodu: 0-1 aralığında random değer oluşturur
np.random.rand(3)
# 0-1 aralığında 3 tane random değer oluşturur
np.random.rand(3)

array([0.52819775, 0.65953589, 0.09457098])

In [25]:
#randn() methodu: eksi değerleride dahil eder
np.random.randn(3)

array([-0.17071558,  1.14902655,  1.92753076])

In [31]:
array1=np.arange(25)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
# array1 içindeki değerli (5*5) matrislerde gösterme
array1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
array2=np.random.randint(1,100,10)

In [34]:
array2

array([34, 13, 76, 90,  2, 41, 51, 53, 78, 38])

In [35]:
# random değerler içerisinden maksimum değeri gösterir 
array2.max()

90

In [37]:
# random değerler içerisinden minumum değeri gösterir 
array2.min()

2

In [40]:
# sum() methodu: random değerlerin toplamı
array2.sum()

476

In [41]:
# mean() methodu: random değerlerin ortalaması
array2.mean()

47.6

In [42]:
#argmin() ve argmax() methodları:
array2.argmin()#min elemana ait indeks değeri

4

In [43]:
array2.argmax()#max elemana ait indeks değeri

3

In [44]:
# determinant hesaplama
determinant=np.random.randint(1,100,25)

In [45]:
determinant=determinant.reshape(5,5)

In [46]:
determinant

array([[27, 54, 94, 89, 41],
       [35, 31, 97, 65, 68],
       [26, 52, 81, 80, 54],
       [47, 35, 42,  5, 69],
       [ 6, 91, 51, 59, 40]])

In [47]:
np.linalg.det(determinant)

-84792432.99999982

In [51]:
det_array=np.array([[2,5],[4,1]])

In [52]:
det_array

array([[2, 5],
       [4, 1]])

In [54]:
np.linalg.det(det_array)

-17.999999999999996

    NUMPY ARRAYLERİN İNDEKSLENMESİ

In [55]:
import numpy as np
array=np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
array[0]

1

In [57]:
array[1:5]

array([2, 3, 4, 5])

In [58]:
array[:5]

array([1, 2, 3, 4, 5])

In [59]:
array[:5:3]

array([1, 4])

In [60]:
#ilk 3 değerin 2 olarak değişimi
array[:3]=2
array

array([2, 2, 2, 4, 5, 6, 7, 8, 9])

In [61]:
#
array2=array

In [62]:
array2

array([2, 2, 2, 4, 5, 6, 7, 8, 9])

In [63]:
array2[:3]=5 

In [64]:
array2 #array2 de yapılan değişim

array([5, 5, 5, 4, 5, 6, 7, 8, 9])

In [65]:
array #array1 de meydana gelen değişim

array([5, 5, 5, 4, 5, 6, 7, 8, 9])

In [70]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr2=arr.copy()

In [73]:
arr2[:3]=5

In [74]:
arr2

array([5, 5, 5, 4, 5, 6, 7, 8, 9])

In [75]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
new_arr=np.arange(1,21)
new_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [77]:
new_arr=new_arr.reshape(5,4)

In [78]:
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [79]:
#satır sütun işlemleri
new_arr[:,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [81]:
new_arr[2:,1:2]

array([[10],
       [14],
       [18]])

In [82]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr<5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [84]:
boolarr=arr<5 #şartı sağlamayanları kaldırır

In [85]:
arr[boolarr]

array([1, 2, 3, 4])

In [86]:
#
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

    NUMPY ARRAY TEMEL İŞLEMLERİ

In [88]:
#array elemanlarının toplamı
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [89]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [90]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [91]:
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [92]:
arr1+5

array([ 6,  7,  8,  9, 10])

In [93]:
arr2*3

array([18, 21, 24, 27, 30])

In [94]:
arr1

array([1, 2, 3, 4, 5])

In [95]:
#karakök hesaplama
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])